"""Add DB

Revision ID: 60852089d4e0
Revises: 
Create Date: 2022-05-29 21:05:13.530957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60852089d4e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
