"""add column lol

Revision ID: 64a6c8e11ce0
Revises: bd7245d0c34c
Create Date: 2022-05-25 15:33:55.664061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a6c8e11ce0'
down_revision = 'bd7245d0c34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lol', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("lol")
    # ### end Alembic commands ###
