"""New miggration

Revision ID: bba7a1272ce6
Revises: c80dc55bddde
Create Date: 2022-05-27 23:09:01.601843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba7a1272ce6'
down_revision = 'c80dc55bddde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
